name: window_manager
description: Playmesh HarmonyOS compile-time compatibility layer.
version: 0.5.2
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
