name: share_plus
description: Playmesh OpenHarmony share_plus compatibility layer.
version: 10.1.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  cross_file: 0.3.4+2
  flutter:
    sdk: flutter
