import 'dart:convert';

import 'package:cryptography/cryptography.dart';

import 'gdevelop_ai_content_policy.dart';

class GDevelopAiProjectContextValidationException implements Exception {
  const GDevelopAiProjectContextValidationException(
    this.code,
    this.message, {
    this.path,
    this.valueType,
  });

  final String code;
  final String message;
  final String? path;
  final String? valueType;

  String? get safeDiagnosticReason =>
      path == null || valueType == null ? null : 'path=$path type=$valueType';

  @override
  String toString() => '$code: $message';
}

/// A bounded, versioned snapshot generated by GDevelop's official project
/// simplifiers. It is prompt context only and is never an authentication or
/// project persistence boundary.
class GDevelopAiProjectContext {
  const GDevelopAiProjectContext._({
    required this._value,
    required this.contentHash,
    required this.encodedBytes,
    required this.sceneNames,
    required this.selectedSceneName,
  });

  static const schemaVersion = '1.0.0';
  static const maxEncodedBytes = 1024 * 1024;
  static const maxSelectedSceneEventsBytes = 256 * 1024;
  static const maxStringBytes = 512 * 1024;
  static const maxDepth = 48;
  static const maxNodes = 100000;

  final Map<String, Object?> _value;
  final String contentHash;
  final int encodedBytes;
  final List<String> sceneNames;
  final String? selectedSceneName;

  Map<String, Object?> sceneIndexJson() => {
    'sceneNames': sceneNames,
    'selectedSceneName': selectedSceneName,
  };

  Map<String, Object?> toJson() => _value;

  Map<String, Object?> metadataJson() => {
    'schemaVersion': schemaVersion,
    'contentHash': contentHash,
    'size': encodedBytes,
    'selectedSceneName': selectedSceneName,
  };

  static Future<Map<String, Object?>> capabilitiesReference(
    Map<String, Object?> canonicalToolContract,
  ) async {
    final canonical = _canonicalizeWithoutLimits(canonicalToolContract);
    final bytes = utf8.encode(jsonEncode(canonical));
    final digest = await Sha256().hash(bytes);
    return Map.unmodifiable({
      'contractHash': _hex(digest.bytes),
      'protocolVersion': canonicalToolContract['protocolVersion'],
      'toolsVersion': canonicalToolContract['toolsVersion'],
      'gdevelopVersion': canonicalToolContract['gdevelopVersion'],
      'upstreamCommit': canonicalToolContract['upstreamCommit'],
      'storeNetworkEnabled': canonicalToolContract['storeNetworkEnabled'],
      'toolCount': canonicalToolContract['toolCount'],
    });
  }

  static Future<GDevelopAiProjectContext> parse(
    Object? raw, {
    required Map<String, Object?> canonicalToolContract,
  }) async {
    if (raw is! Map) {
      throw const GDevelopAiProjectContextValidationException(
        'project_context_invalid',
        'GDevelop AI project context 必须是对象',
      );
    }
    final envelope = _stringMap(raw, r'$');
    _requireExactKeys(envelope, const {
      'schemaVersion',
      'selectedScene',
      'projectSummary',
      'capabilities',
    }, r'$');
    if (envelope['schemaVersion'] != schemaVersion) {
      throw const GDevelopAiProjectContextValidationException(
        'project_context_version_unsupported',
        '不支持的 GDevelop AI project context schemaVersion',
      );
    }

    final summary = _requiredMap(
      envelope['projectSummary'],
      r'$.projectSummary',
    );
    _requireExactKeys(summary, const {
      'simplifiedProject',
      'projectSpecificExtensionsSummary',
    }, r'$.projectSummary');
    final simplifiedProject = _requiredMap(
      summary['simplifiedProject'],
      r'$.projectSummary.simplifiedProject',
    );
    _requireFields(simplifiedProject, const {
      'properties',
      'globalObjects',
      'globalObjectGroups',
      'scenes',
      'globalVariables',
      'resources',
    }, r'$.projectSummary.simplifiedProject');
    final properties = _requiredMap(
      simplifiedProject['properties'],
      r'$.projectSummary.simplifiedProject.properties',
    );
    if (properties['gameResolutionWidth'] is! num ||
        properties['gameResolutionHeight'] is! num) {
      throw const GDevelopAiProjectContextValidationException(
        'project_context_invalid',
        'GDevelop SimplifiedProject.properties 缺少官方分辨率字段',
      );
    }
    for (final field in const [
      'globalObjects',
      'globalObjectGroups',
      'scenes',
      'globalVariables',
      'resources',
    ]) {
      if (simplifiedProject[field] is! List) {
        throw GDevelopAiProjectContextValidationException(
          'project_context_invalid',
          'GDevelop SimplifiedProject.$field 必须是数组',
        );
      }
    }
    final extensionSummary = _requiredMap(
      summary['projectSpecificExtensionsSummary'],
      r'$.projectSummary.projectSpecificExtensionsSummary',
    );
    if (extensionSummary['extensionSummaries'] is! List) {
      throw const GDevelopAiProjectContextValidationException(
        'project_context_invalid',
        'GDevelop ExtensionSummary.extensionSummaries 必须是数组',
      );
    }
    for (final rawScene in simplifiedProject['scenes']! as List) {
      final scene = _requiredMap(
        rawScene,
        r'$.projectSummary.simplifiedProject.scenes[]',
      );
      if (scene['sceneName'] is! String ||
          (scene['sceneName']! as String).isEmpty ||
          scene['objects'] is! List ||
          scene['objectGroups'] is! List ||
          scene['sceneVariables'] is! List ||
          scene['layers'] is! List ||
          scene['instancesOnSceneDescription'] is! String) {
        throw const GDevelopAiProjectContextValidationException(
          'project_context_invalid',
          'GDevelop SimplifiedProject.scenes 不是官方 SimplifiedScene 结构',
        );
      }
    }
    for (final rawResource in simplifiedProject['resources']! as List) {
      final resource = _requiredMap(
        rawResource,
        r'$.projectSummary.simplifiedProject.resources[]',
      );
      if (resource['name'] is! String ||
          resource['type'] is! String ||
          resource['file'] is! String ||
          (resource['metadata'] != null && resource['metadata'] is! String)) {
        throw const GDevelopAiProjectContextValidationException(
          'project_context_invalid',
          'GDevelop SimplifiedProject.resources 不是官方 SimplifiedResource 结构',
        );
      }
    }
    for (final rawExtension
        in extensionSummary['extensionSummaries']! as List) {
      final extension = _requiredMap(
        rawExtension,
        r'$.projectSummary.projectSpecificExtensionsSummary.extensionSummaries[]',
      );
      if (extension['extensionName'] is! String ||
          extension['extensionFullName'] is! String ||
          extension['description'] is! String ||
          extension['shortDescription'] is! String ||
          extension['dimension'] is! String ||
          extension['freeActions'] is! List ||
          extension['freeConditions'] is! List ||
          extension['freeExpressions'] is! List ||
          extension['objects'] is! Map ||
          extension['behaviors'] is! Map ||
          extension['effects'] is! Map) {
        throw const GDevelopAiProjectContextValidationException(
          'project_context_invalid',
          'GDevelop ExtensionSummary 不是官方结构',
        );
      }
    }

    final expectedCapabilities = await capabilitiesReference(
      canonicalToolContract,
    );
    final capabilities = _requiredMap(
      envelope['capabilities'],
      r'$.capabilities',
    );
    _requireExactKeys(
      capabilities,
      expectedCapabilities.keys.toSet(),
      r'$.capabilities',
    );
    if (jsonEncode(_canonicalizeWithoutLimits(capabilities)) !=
        jsonEncode(_canonicalizeWithoutLimits(expectedCapabilities))) {
      throw const GDevelopAiProjectContextValidationException(
        'project_context_capabilities_mismatch',
        'ProjectContext capabilities 必须引用当前 Gateway 工具合约',
      );
    }

    final sceneNames = <String>[];
    final sceneNameSet = <String>{};
    for (final rawScene in simplifiedProject['scenes']! as List) {
      if (rawScene is! Map) continue;
      final name = rawScene['sceneName'];
      if (name is String && name.isNotEmpty && sceneNameSet.add(name)) {
        sceneNames.add(name);
      }
    }
    final rawSelectedScene = envelope['selectedScene'];
    String? selectedSceneName;
    if (rawSelectedScene != null) {
      final selectedScene = _requiredMap(rawSelectedScene, r'$.selectedScene');
      _requireExactKeys(selectedScene, const {
        'name',
        'eventsText',
      }, r'$.selectedScene');
      final name = selectedScene['name'];
      final eventsText = selectedScene['eventsText'];
      if (name is! String || name.isEmpty || eventsText is! String) {
        throw const GDevelopAiProjectContextValidationException(
          'project_context_selected_scene_invalid',
          'selectedScene 必须包含非空 name 和 eventsText',
        );
      }
      if (!sceneNameSet.contains(name)) {
        throw const GDevelopAiProjectContextValidationException(
          'project_context_selected_scene_missing',
          'selectedScene 不在 SimplifiedProject.scenes 中',
        );
      }
      if (eventsText.trim() == 'Error while rendering events as text.') {
        throw const GDevelopAiProjectContextValidationException(
          'project_context_events_render_failed',
          '当前场景事件文本生成失败',
        );
      }
      if (utf8.encode(eventsText).length > maxSelectedSceneEventsBytes) {
        throw const GDevelopAiProjectContextValidationException(
          'project_context_selected_scene_too_large',
          '当前场景事件文本超过 256 KiB',
        );
      }
      selectedSceneName = name;
    }

    final budget = _ValidationBudget();
    final canonical = _canonicalize(envelope, r'$', 0, budget);
    final bytes = utf8.encode(jsonEncode(canonical));
    if (bytes.length > maxEncodedBytes) {
      throw const GDevelopAiProjectContextValidationException(
        'project_context_too_large',
        'GDevelop AI project context 超过 1 MiB',
      );
    }
    final digest = await Sha256().hash(bytes);
    return GDevelopAiProjectContext._(
      value: Map.unmodifiable(Map<String, Object?>.from(canonical as Map)),
      contentHash: _hex(digest.bytes),
      encodedBytes: bytes.length,
      sceneNames: List.unmodifiable(sceneNames),
      selectedSceneName: selectedSceneName,
    );
  }
}

class _ValidationBudget {
  int nodes = 0;
}

Object? _canonicalize(
  Object? value,
  String path,
  int depth,
  _ValidationBudget budget,
) {
  if (depth > GDevelopAiProjectContext.maxDepth) {
    throw const GDevelopAiProjectContextValidationException(
      'project_context_too_deep',
      'GDevelop AI project context 嵌套过深',
    );
  }
  budget.nodes += 1;
  if (budget.nodes > GDevelopAiProjectContext.maxNodes) {
    throw const GDevelopAiProjectContextValidationException(
      'project_context_too_complex',
      'GDevelop AI project context 节点过多',
    );
  }
  if (value == null || value is bool || value is int) return value;
  if (value is double) {
    if (!value.isFinite) {
      throw GDevelopAiProjectContextValidationException(
        'project_context_invalid_number',
        '$path 包含非有限数值',
      );
    }
    return value;
  }
  if (value is String) {
    if (utf8.encode(value).length > GDevelopAiProjectContext.maxStringBytes) {
      throw GDevelopAiProjectContextValidationException(
        'project_context_string_too_large',
        '$path 字符串超过 512 KiB',
      );
    }
    _rejectSensitiveString(value, path);
    return value;
  }
  if (value is List) {
    return List.unmodifiable([
      for (var index = 0; index < value.length; index++)
        _canonicalize(value[index], '$path[$index]', depth + 1, budget),
    ]);
  }
  if (value is Map) {
    final map = _stringMap(value, path);
    final keys = map.keys.toList()..sort();
    return Map.unmodifiable({
      for (final key in keys)
        key: _canonicalize(map[key], '$path.$key', depth + 1, budget),
    });
  }
  throw GDevelopAiProjectContextValidationException(
    'project_context_not_json',
    '$path 不是 JSON 值',
  );
}

Object? _canonicalizeWithoutLimits(Object? value) {
  if (value == null || value is bool || value is num || value is String) {
    return value;
  }
  if (value is List) {
    return [for (final item in value) _canonicalizeWithoutLimits(item)];
  }
  if (value is Map) {
    // Tool contracts are declared by the active WebIDE. Their field names are
    // data, not ProjectContext content, so names such as `url`, `token` or
    // `bridge` must participate in the hash instead of being rejected by the
    // ProjectContext sensitive-content policy.
    final map = _stringMapWithoutContentPolicy(value);
    final keys = map.keys.toList()..sort();
    return {for (final key in keys) key: _canonicalizeWithoutLimits(map[key])};
  }
  throw const GDevelopAiProjectContextValidationException(
    'project_context_not_json',
    '工具能力合约不是 JSON',
  );
}

Map<String, Object?> _stringMapWithoutContentPolicy(Map value) {
  final result = <String, Object?>{};
  for (final entry in value.entries) {
    if (entry.key is! String) {
      throw const GDevelopAiProjectContextValidationException(
        'project_context_not_json',
        '工具能力合约包含非字符串键',
      );
    }
    result[entry.key as String] = entry.value;
  }
  return result;
}

Map<String, Object?> _requiredMap(Object? value, String path) {
  if (value is! Map) {
    throw GDevelopAiProjectContextValidationException(
      'project_context_invalid',
      '$path 必须是对象',
    );
  }
  return _stringMap(value, path);
}

Map<String, Object?> _stringMap(Map value, String path) {
  final result = <String, Object?>{};
  for (final entry in value.entries) {
    if (entry.key is! String) {
      throw GDevelopAiProjectContextValidationException(
        'project_context_not_json',
        '$path 包含非字符串键',
      );
    }
    final key = entry.key as String;
    _rejectSensitiveKey(key, '$path.$key');
    result[key] = entry.value;
  }
  return result;
}

void _requireExactKeys(
  Map<String, Object?> value,
  Set<String> expected,
  String path,
) {
  final actual = value.keys.toSet();
  if (actual.length != expected.length ||
      !actual.containsAll(expected) ||
      !expected.containsAll(actual)) {
    throw GDevelopAiProjectContextValidationException(
      'project_context_invalid',
      '$path 字段必须精确为 ${expected.toList()..sort()}',
    );
  }
}

void _requireFields(
  Map<String, Object?> value,
  Set<String> required,
  String path,
) {
  if (!value.keys.toSet().containsAll(required)) {
    throw GDevelopAiProjectContextValidationException(
      'project_context_invalid',
      '$path 缺少官方 SimplifiedProject 根字段',
    );
  }
}

void _rejectSensitiveKey(String key, String path) {
  final violation = GDevelopAiContentPolicy.inspectKey(key, path);
  if (violation != null) {
    throw GDevelopAiProjectContextValidationException(
      'project_context_sensitive_field',
      '${violation.path} 不允许出现在 ProjectContext',
      path: violation.path,
      valueType: 'field',
    );
  }
}

void _rejectSensitiveString(String value, String path) {
  final violation = GDevelopAiContentPolicy.inspectString(value, path);
  if (violation == null) return;
  switch (violation.kind) {
    case GDevelopAiSensitiveContentKind.urlOrToken:
      throw GDevelopAiProjectContextValidationException(
        'project_context_url_or_token_forbidden',
        '${violation.path} 不允许包含 URL 或鉴权信息',
        path: violation.path,
        valueType: 'string',
      );
    case GDevelopAiSensitiveContentKind.bridge:
      throw GDevelopAiProjectContextValidationException(
        'project_context_bridge_forbidden',
        '${violation.path} 不允许包含 Playmesh bridge/runtime 内容',
        path: violation.path,
        valueType: 'string',
      );
    case GDevelopAiSensitiveContentKind.sensitiveField:
      throw StateError('字符串检查返回了字段违规类型');
  }
}

String _hex(List<int> bytes) =>
    bytes.map((byte) => byte.toRadixString(16).padLeft(2, '0')).join();
